version: '2'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:3.2.1
        container_name: zookeeper
        network_mode: "host"
        environment:
          - ZOOKEEPER_CLIENT_PORT=2181
    kafka:
        image: confluentinc/cp-kafka:3.2.1
        container_name: kafka
        network_mode: "host"
        environment:
          - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
          - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
          - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    schema-registry:
        image: confluentinc/cp-schema-registry:3.2.1
        container_name: schema-registry
        network_mode: "host"
        environment:
          - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:2181
          - SCHEMA_REGISTRY_HOST_NAME=localhost
          - SCHEMA_REGISTRY_LISTENERS=http://localhost:8081